site_name: ABSESpy

nav:
    - Home:
        - AB-SESpy: index.md
        - Installation: home/Installation.md
        - Guide Checklist: home/guide_checklist.md
        - Getting started: home/get_started.md
        - Dependencies: home/dependencies.md
        - License: home/license.md
        - Contributions: home/contribution.md
        - Acknowledge: home/acknowledge.md
        # - RoadMap: home/roadmap.md
    - Wiki:
        - Wiki: wiki/wiki.md
        - Refers: wiki/about.md
        - Materials: wiki/materials.md
        - Concepts: wiki/concepts.md
        - Paper: paper/paper.md
    - Tutorials:
        - Tutorial: tutorial/tutorial.md
        - Start from ABM: tutorial/tutorial_guide_from_ABM.md
        - Start from SES: tutorial/tutorial_guide_from_SES.md
        - Beginner Level:
          - B01: tutorial/beginner/get_started.ipynb
          - B02: tutorial/beginner/organize_model_structure.ipynb
          - B03: tutorial/beginner/time_control.ipynb
          - B04: tutorial/beginner/manage_parameters.ipynb
          - B05: tutorial/beginner/actors.ipynb
          - B06: tutorial/beginner/movement.ipynb
          - B07: tutorial/beginner/predation_tutorial.ipynb
          - B08: tutorial/beginner/hotelling_tutorial.ipynb
        - Advanced Level:
          - A01: tutorial/advanced/geodata.ipynb
          # - A02: tutorial/advanced/human_behavior_simulation.ipynb  # File not found
        - Competing Level:
          - C01: tutorial/completing/fire_tutorial.ipynb
          - C02: tutorial/completing/linking_actors.ipynb
    - Examples:
        - Official Examples: examples/official.md
        - Gallery: examples/gallery.md
        - Community Examples: examples/community.md
    - API references:
        - API: api/api.md
        - Model structure:
          - Main Model: api/model.md
          - Natural Modules: api/nature.md
          - PatchModule (layer): api/layer.md
          - Human Modules: api/human.md
          - Cells: api/cells.md
        - Actors' Operation:
          - Actor (Agent): api/agents.md
          - Actors Container: api/container.md
          - Actors List: api/sequences.md
          - Movements: api/move.md
          - Interlinks: api/links.md
        - Workflow Control:
          - Time Control: api/time.md
          - Random: api/random.md
          - Experiment: api/experiment.md

theme:
    name: "material"
    logo: "https://songshgeo-picgo-1302043007.cos.ap-beijing.myqcloud.com/uPic/logo_abses.svg"
    palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    language: en
    features:
        - header.autohide
        - navigation.tabs
        - navigation.tracking
        - toc.follow
        - content.tooltips  # only sponsor
        - content.code.copy
        - content.tooltips
plugins:
    - search
    - mkdocs-jupyter:
        include_source: True
        execute: true  # Now executing notebooks with updated API
        allow_errors: true
    # i18n plugin conflicts with mkdocs-jupyter
    # Solution: Use Material tabs for bilingual content in .md files
    # Notebooks will remain English-only
    # - i18n:
    #     docs_structure: suffix
    #     fallback_to_default: true
    #     reconfigure_material: true
    #     reconfigure_search: true
    #     languages:
    #       - locale: en
    #         default: true
    #         name: English
    #         build: true
    #       - locale: zh
    #         name: 中文
    #         build: true
    #     nav_translations:
    #                       Home: 首页
    #                       Installation: 安装
    #                       Getting started: 快速开始
    #                       Guide Checklist: 指南检查清单
    #                       Dependencies: 依赖项
    #                       License: 许可证
    #                       Contributions: 贡献
    #                       Acknowledge: 致谢
    #                       Wiki: 维基
    #                       Refers: 参考
    #                       Materials: 材料
    #                       Concepts: 概念
    #                       Paper: 论文
    #                       Tutorials: 教程
    #                       Tutorial: 教程
    #                       Start from ABM: 从ABM开始
    #                       Start from SES: 从SES开始
    #                       Beginner Level: 初级教程
    #                       Advanced Level: 高级教程
    #                       Competing Level: 完善教程
    #                       Examples: 示例
    #                       Official Examples: 官方示例
    #                       Gallery: 画廊
    #                       Community Examples: 社区示例
    #                       API references: API参考
    #                       Model structure: 模型结构
    #                       Main Model: 主模型
    #                       Natural Modules: 自然模块
    #                       PatchModule (layer): 网格模块
    #                       Human Modules: 人类模块
    #                       Cells: 单元格
    #                       Actors' Operation: 智能体操作
    #                       Actor (Agent): 智能体
    #                       Actors Container: 智能体容器
    #                       Actors List: 智能体列表
    #                       Movements: 移动
    #                       Interlinks: 连接
    #                       Workflow Control: 工作流控制
    #                       Time Control: 时间控制
    #                   Random: 随机
    #                   Experiment: 实验
    # - markdown-exec
    - mkdocstrings:
        handlers:
          python:
            paths: ["."]
            inventories:
              - https://docs.python.org/3/objects.inv
            options:
              members_order: source
              separate_signature: true
              filters: ["!^_"]
              docstring_options:
                ignore_init_summary: true
              merge_init_into_class: true
              show_root_heading: true
              show_source: true
              find_stubs_package: true
    - exclude:
        glob:
          - plugins/*
          - __pycache__/*
    - bibtex:
        bib_file: "docs/refs.bib"
    # - mkdocs-simple-hooks:  # Temporarily disabled - docs.plugins.checks module missing
    #     hooks:
    #       on_pre_build: 'docs.plugins.checks:on_pre_build'
    - macros
    - callouts
    - glightbox
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/
    - tags
    - mike:
        alias_type: symlink
        canonical_version: latest
    # - typeset

extra:
  alternate:
    - name: English
      link:
      lang: en
    - name: Chinese
      link: /ch/
      lang: ch
  # https://squidfunk.github.io/mkdocs-material/setup/setting-up-versioning/
  version:
    - provider: mike
  tags:
    model: tag


markdown_extensions:
  - attr_list
  - admonition
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences

  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - footnotes
  - toc:
      baselevel: 2
      separator: "-"
      permalink: true
      title: Page contents
  - attr_list
  - md_in_html
  - pymdownx.tasklist:
      custom_checkbox: true
  - abbr

  # https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/#search
  # 表情符号拓展
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

  # 以下配置参考 https://github.com/pydantic/pydantic/blob/main/mkdocs.yml#L6C6-L6C6
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.extra
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/SongshGeoLab/ABSESpy
    # - icon: fontawesome/brands/web
    #   link: https://cv.songshgeo.com/
repo_url: https://github.com/SongshGeoLab/ABSESpy
