defaults:
  - default
  - _self_

exp:
  name: fire_spread
  outdir: out
  repeats: 11

reports:
  final:
    burned_rate: "burned_rate"


model:
  density: 0.7
  shape:
    - 100
    - 100

time:
  end: 100

log:
  name: fire_spread
  level: INFO
  console: false
