name: gh-page
on:
  push:
    branches:
      - master
      - main
      - dev
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.repository.fork == false
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Cache Poetry and dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pypoetry
            .venv
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: latest
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Install dependencies
        run: |
          poetry run pip install --upgrade pip
          set -e
          poetry run pip install git+https://${{ secrets.GH_TOKEN }}@github.com/squidfunk/mkdocs-material-insiders.git
          poetry install
      - name: Deploy documentation (dev branch)
        if: github.ref == 'refs/heads/dev'
        run: poetry run mike deploy --push dev
      
      - name: Deploy documentation (master branch)
        if: github.ref == 'refs/heads/master'
        run: |
          poetry run mike deploy --push --update-aliases 0.8 latest
          poetry run mike set-default --push latest
      
      - name: Deploy documentation (version tags)
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          MAJOR_MINOR=$(echo $VERSION | cut -d. -f1-2)
          poetry run mike deploy --push --update-aliases $MAJOR_MINOR latest
          poetry run mike set-default --push latest
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
